name: CI

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  check:
    name: Cargo checks
    runs-on: ubuntu-latest
    strategy:
      matrix:
        crate: [atlas, remote-client, switchboard]
    env:
      SCCACHE_GHA_ENABLED: "true"
      RUSTC_WRAPPER: "sccache"
    steps:
      - uses: actions/checkout@v6
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy, rustfmt
      - uses: mozilla-actions/sccache-action@bafd42bd91680affe190f697cac6ef3ad958ecba

      - name: cargo check
        run: cargo check --manifest-path ${{ matrix.crate }}/Cargo.toml --workspace --all-targets

      - name: cargo fmt
        run: cargo fmt --manifest-path ${{ matrix.crate }}/Cargo.toml --all --check

      - name: cargo clippy
        run: cargo clippy --manifest-path ${{ matrix.crate }}/Cargo.toml -- -D warnings

  test:
    name: Cargo tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        crate: [atlas, remote-client, switchboard]
    env:
      SCCACHE_GHA_ENABLED: "true"
      RUSTC_WRAPPER: "sccache"
    steps:
      - uses: actions/checkout@v6
      - uses: dtolnay/rust-toolchain@stable
      - uses: mozilla-actions/sccache-action@bafd42bd91680affe190f697cac6ef3ad958ecba

      - name: cargo test ${{ matrix.crate }}
        run: cargo test --manifest-path ${{ matrix.crate }}/Cargo.toml --workspace --all-targets

  docs:
    name: docs.rs test build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        module: [atlas, remote-client, switchboard]
        crate: [client, protocol]
    env:
      RUSTDOCFLAGS: -Dwarnings
      SCCACHE_GHA_ENABLED: "true"
      RUSTC_WRAPPER: "sccache"
    steps:
      - uses: actions/checkout@v6
      - uses: dtolnay/rust-toolchain@nightly
      - uses: dtolnay/install@cargo-docs-rs
      - uses: mozilla-actions/sccache-action@v0.0.9

      - name: cargo docs-rs
        run: cargo +nightly docs-rs --manifest-path ${{ matrix.module }}/Cargo.toml -p selium-${{ matrix.module }}-${{ matrix.crate }}

  # @todo: still relies on external file path to selium-server bin
  # integration:
  #   name: Cargo integration tests
  #   runs-on: ubuntu-latest
  #   strategy:
  #     matrix:
  #       crate: [tests/request-reply]
  #   env:
  #     SCCACHE_GHA_ENABLED: "true"
  #     RUSTC_WRAPPER: "sccache"
  #   steps:
  #     - uses: actions/checkout@v6
  #     - uses: dtolnay/rust-toolchain@stable
  #       with:
  #         targets: wasm32-unknown-unknown
  #     - uses: mozilla-actions/sccache-action@bafd42bd91680affe190f697cac6ef3ad958ecba

  #     - name: cargo test ${{ matrix.crate }}
  #       run: cargo test --manifest-path ${{ matrix.crate }}/Cargo.toml
