name: CI

permissions:
  contents: read

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  check:
    name: Cargo checks
    runs-on: ubuntu-latest
    strategy:
      matrix:
        crate: [atlas, remote-client, switchboard]
    env:
      SCCACHE_GHA_ENABLED: "true"
      RUSTC_WRAPPER: "sccache"
    steps:
      - uses: actions/checkout@v6
      - uses: dtolnay/rust-toolchain@f7ccc83f9ed1e5b9c81d8a67d7ad1a747e22a561
        with:
          toolchain: stable
          components: clippy, rustfmt
      - uses: mozilla-actions/sccache-action@7d986dd989559c6ecdb630a3fd2557667be217ad # v0.0.9

      - name: cargo check
        run: cargo check --manifest-path ${{ matrix.crate }}/Cargo.toml --workspace --all-targets

      - name: cargo fmt
        run: cargo fmt --manifest-path ${{ matrix.crate }}/Cargo.toml --all --check

      - name: cargo clippy
        run: cargo clippy --manifest-path ${{ matrix.crate }}/Cargo.toml -- -D warnings

  test:
    name: Cargo tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        crate: [atlas, remote-client, switchboard]
    env:
      SCCACHE_GHA_ENABLED: "true"
      RUSTC_WRAPPER: "sccache"
    steps:
      - uses: actions/checkout@v6
      - uses: dtolnay/rust-toolchain@f7ccc83f9ed1e5b9c81d8a67d7ad1a747e22a561
        with:
          toolchain: stable
      - uses: mozilla-actions/sccache-action@7d986dd989559c6ecdb630a3fd2557667be217ad # v0.0.9

      - name: cargo test ${{ matrix.crate }}
        run: cargo test --manifest-path ${{ matrix.crate }}/Cargo.toml --workspace --all-targets

  docs:
    name: docs.rs test build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        crate: [atlas, remote-client, switchboard]
    env:
      RUSTDOCFLAGS: -Dwarnings
      SCCACHE_GHA_ENABLED: "true"
      RUSTC_WRAPPER: "sccache"
    steps:
      - uses: actions/checkout@v6
      - uses: dtolnay/rust-toolchain@f7ccc83f9ed1e5b9c81d8a67d7ad1a747e22a561
        with:
          toolchain: nightly
      - uses: dtolnay/install@97c306b4fb754e1dbe18619415cf4a90ae0aa6a2
        with:
          crate: cargo-docs-rs
      - uses: mozilla-actions/sccache-action@7d986dd989559c6ecdb630a3fd2557667be217ad # v0.0.9

      - name: cargo docs-rs
        run: cargo +nightly docs-rs --manifest-path ${{ matrix.crate }}/Cargo.toml -p selium-${{ matrix.crate }}

  # @todo: still relies on external file path to selium-server bin
  # integration:
  #   name: Cargo integration tests
  #   runs-on: ubuntu-latest
  #   strategy:
  #     matrix:
  #       crate: [tests/request-reply]
  #   env:
  #     SCCACHE_GHA_ENABLED: "true"
  #     RUSTC_WRAPPER: "sccache"
  #   steps:
  #     - uses: actions/checkout@v6
  #     - uses: dtolnay/rust-toolchain@stable
  #       with:
  #         targets: wasm32-unknown-unknown
  #     - uses: mozilla-actions/sccache-action@7d986dd989559c6ecdb630a3fd2557667be217ad # v0.0.9

  #     - name: cargo test ${{ matrix.crate }}
  #       run: cargo test --manifest-path ${{ matrix.crate }}/Cargo.toml
